### ISSUE TITLE
API - Synchronous operations are disallowed

### ISSUE THREAD

**Issue by bluetd** [Manager-io/Manager.zip#3]
The latest version for Ubuntu started returning an error when using the POST method of the API as following:

400 Bad Request System.InvalidOperationException: Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.
--
  | at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count)
  | at System.IO.StreamReader.ReadBuffer()
  | at System.IO.StreamReader.ReadToEnd()
  | at ManagerServer.HttpHandlers.Api.Api.Post() in C:\projects\manager\ManagerServer\HttpHandlers\Api\Api.cs:line 256

I think you should allow the Synchronous operations through the code or the Kestrel config, as it should be allowed for standard HTTP APIs.

Thanks in Advanced

**Comment by lubos** [comment]
The latest version has fixed the issue.
